FROM node:20-bookworm

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libpq-dev \
    postgresql-client \
    curl \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /digichat

RUN chown -R node:node ./

RUN echo "node ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER node
# pnpmのインストール
RUN SHELL=/bin/bash curl -fsSL https://get.pnpm.io/install.sh | bash -

# gitのgpg署名の設定
RUN if git config --global --get gpg.ssh.program; then \
        git config --global --unset gpg.ssh.program; \
    fi

# コンテナ起動時のコマンド
CMD ["/bin/bash"]