services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Tokyo
      - POSTGRES_INITDB_ARGS=--locale=ja_JP.utf8
    volumes:
      - digichat-db:/var/lib/postgresql/data
    container_name: digichat-db
    restart: always
volumes:
  digichat-db: