import type { Metadata } from "next";

import { MantineProvider } from "@mantine/core";
import dayjs from "dayjs";
import timezone from "dayjs/plugin/timezone";
import utc from "dayjs/plugin/utc";

import "@mantine/core/styles.css";
import AppShell from "./_components/AppShell";
import "./globals.css";

dayjs.extend(utc);
dayjs.extend(timezone);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootRayoutProps = {
  children: React.ReactNode;
  modal: React.ReactNode;
};

export default function RootLayout({ children, modal }: RootRayoutProps) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <AppShell>{children}</AppShell>
          {modal}
        </MantineProvider>
      </body>
    </html>
  );
}
