name: Test Repository

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Docker Compose のバージョン確認
        run: |
          docker compose --version

      - name: テスト用DBを起動
        run: |
          docker compose -f compose.yml --env-file .env.test up -d

      - name: Postgres の起動待機
        run: |
          for i in {1..10}; do
            if docker exec digichat-db pg_isready -U postgres; then
              echo "Postgres is ready!"
              exit 0
            fi
            echo "Waiting for Postgres..."
            sleep 2
          done
          echo "Postgres did not become ready in time." >&2
          exit 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: テスト用DBのマイグレーション
        run: make migrate-test

      - name: リポジトリテストの実行
        run: make t-repo

      - name: Docker Compose の停止
        if: always()
        run: docker compose -f compose.yml --env-file .env.test down
